py:
    volumes:
        - ./code:/code
    dockerfile: dockerfile_py3web
    build: ./
    ports:
        - "8092:8092"
    links:
        - mysql
    restart: always
mysql:
    image: registry.cn-hangzhou.aliyuncs.com/qinyujia-test/mysql
    environment:
        MYSQL_ROOT_PASSWORD: "pwd123456"
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    volumes:
        - "./dbdump:/docker-entrypoint-initdb.d"
